name: Path on Push trigger

on: 
  push:
    paths:
    - 'src/**'
    - '!src/data/**'
  
jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      max-parallel: 2
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      if: strategy == max-parallel 
      run: echo Checking on if condition here...!
    - name: Run a multi-line script
      if: strategy == !max-parallel
      run: |
        echo Checking on If Condition 
        echo in the on push trigger with strategy matrix and max-parallel.
        
