name: Path on Push and Fork trigger

on: push
#    paths:
#    - 'src/**'
#    - '!src/data/**'
#  fork:
jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
      max-parallel: 2
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      if: github.repository == 'PhanindraReddyP/GitHubActions' && github.event_name == 'push'
      run: echo Checking on if condition here...!
    - name: Run a multi-line script
      if: github.event_name == 'fork'
      run: |
        pwd 
        ls
        ll
        echo Checking on If Condition 
        echo in the on push trigger with strategy matrix and max-parallel.
        
